name: absorption
channels:
  - conda-forge
dependencies:
  - gdal
  - pdal
  - python-pdal
  - matplotlib
  - numpy
  - python
  - whitebox_tools
  - pip
  - pyproj
  - shapely
  - geocoder
  - pip:
    - requests
