name: Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pdal-plugins
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v4
    - name: Setup micromamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        python-version: "3.11"
        auto-update-conda: true
        environment-file: environment.yml

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install build pipx twine
        pipx run build --sdist

    - name: Publish package distributions to PyPI
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: pypa/gh-action-pypi-publish@release/v1

